databases:
  - name: forum
    databaseName: forum
    user: forum

services:
  - type: web
    name: forum
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: forum
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
